---
- name: Deployment of a fault-tolerant NGINX-based web server
  hosts: app
  gather_facts: false
  become: true 

  tasks: 
    - name: Change ssh port to 1834
      set_fact:
        ansible_port: 1834

    - name: Change ansible_python_interpreter 
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

    - name: Build images on a VM using Dockerfile in the skillcloud-nsinx directory
      docker_image:
        name: '{{ item.name }}'
        build:
          path: /skillcloud-nginx/{{ item.path }}
      loop: 
        - { name: site, path: site }
        - { name: balance, path: balance }

    - name: Pip install docker-compose
      pip: 
        name: docker-compose

    - name: Launching docker-compose.yml for container assembly
      docker_compose:
        project_src: /skillcloud-nginx
        files:
          - docker-compose.yml 