---
- name: Automating the basic configuration of virtual machines
  hosts: app
  become: true 

  tasks: 
    - name: Update package lists, perform curl installation
      apt: 
        name: 'curl'
        state: latest
        update_cache: true

    - name: Activate the UFW firewall, allow TCP ports 80,8080,1834
      ufw:
        rule: allow
        port: '{{ item }}'
        proto: tcp 
        state: enabled
      loop: 
        - '22'
        - '80'
        - '8080'
        - '1834'

    - name: Change the SSH configuration file | Connection port should be 1834
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^Port"
        line: 'Port 1834'

    - name: Change SSH configuration file | Allow public key authorization
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        line: '{{ item }}'
      loop: 
        - RSAAuthentication yes
        - PubkeyAuthentication yes
        - AuthorizedKeysFile     %h/.ssh/authorized_keys

    - name: Create users to access virtual machines
      ansible.builtin.user:
        name: "{{ item.username }}"
        password: "{{ item.userpass }}"
      loop:
         - { username: 'Webdeveloper', userpass: 'S52we9V6QTp7' }
         - { username: 'Devopsengineer', userpass: 'dHy6sKGHsj2T' }
         - { username: 'Projectmanager', userpass: 'oP92ugMSaCbe' }      

    - name: A public key must be placed for each user
      authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ id_rsa_pub }}"
      loop: 
        - Webdeveloper
        - Devopsengineer
        - Projectmanager
      vars:
        id_rsa_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCovvBkeLIDsvbCyQsMWtPWVgGVKcwAqRONiBJ9JyrVCQbruyMPutatjSlhNpYXKLlP4BXHrGrmAVqeI155li1fkNP5Il7viHRE0HvA3M2extNGDDCiX5f5OlIeT9p/D9OHvWWozLjN2NAGEW24feuzKPZb6Kyv2W3yHbiIU3wt8v50VAIA2+PAfElHp1jplGHQLmYuT6Cc26Pn3WYXZ8t8oU77T6Ki5qDG5V5DVZI3Ym5gqqXXtJYzET9piJvO6qiIcgljtOGlUH9H9QNLEbuF+RKIhL3pFAnF8S79Km2A3j9KFZw6prDR6/VeMffMrNSZLeYztzDGEzm35uz5q6j+qrKsuA4SfpbSOcBwaariOoKpb6JfogoJRgCqxR5O1AKR/Oqhdk6JOlKJk+tIXFmOczH7da/W93f8KGGve4iHRvz/e3vYA7exXIVkD8mc/VmIoT1kqh/uNGia/adnyCgvMpL8JXLJgY2DThpjHslUr0RTEpQJTLTka3D43YV37kM="

    - name: Install the Docker package | Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install the Docker package | Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Install the Docker package | Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Install the Docker package | Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install the Docker package | Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install the Docker package | Install Docker Module for Python
      pip:
        name: docker